# Copyright (c) 2009 & onwards. MapR Tech, Inc., All rights reserved
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: test-snapshot
  namespace: test-csi
spec:
  volumeSnapshotClassName: test-snapshotclass
  source:
    persistentVolumeClaimName: test-dynamic-pvc