# Copyright (c) 2009 & onwards. MapR Tech, Inc., All rights reserved
apiVersion: v1
kind: Pod
metadata:
  name: test-dynamic-block-pod
  namespace: test-csi
spec:
  containers:
  - name: fc-container
    image: fedora:26
    command: ["/bin/sh", "-c"]
    args: [ "tail -f /dev/null" ]
    resources:
      requests:
        memory: "4Gi"
        cpu: "500m"
    volumeDevices:
    - devicePath: /dev/xvda
      name: block
  volumes:
    - name: block
      persistentVolumeClaim:
        claimName: test-dynamic-block-pvc