# Copyright (c) 2009 & onwards. MapR Tech, Inc., All rights reserved
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test-dynamic-sc
  namespace: test-csi
provisioner: com.mapr.csi-kdf
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
    csiProvisionerSecretName: "mapr-provisioner-secrets"
    csiProvisionerSecretNamespace: "test-csi"
    restServers: CHANGETHIS
    cldbHosts: CHANGETHIS
    cluster: CHANGETHIS
    securityType: CHANGETHIS # Default: unsecure
    namePrefix: CHANGETHIS
    mountPrefix: CHANGETHIS
    logLevel: "error"
    retainLogs: "false"
    rootdirperms: "766"
    advisoryquota: CHANGETHIS