kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: testcsi-dynamic-pvc-restore
  namespace: test-csi
spec:
  storageClassName: test-snapshotclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  dataSource:
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
    name: test-snapshot
---
apiVersion: v1
kind: Pod
metadata:
  name: testcsi-snapshot-restore-pod
  namespace: test-csi
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "1000000"
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
    volumeMounts:
    - mountPath: /data
      name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: testcsi-dynamic-pvc-restore