# Default values for hpe-ezmeral-csi-driver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

pullPolicy: IfNotPresent

nodeImage: docker.io/maprtech/csi-kdfplugin:1.2.10
controllerImage: docker.io/maprtech/csi-kdfprovisioner:1.2.8
