apiVersion: v1
kind: SecurityContextConstraints
metadata:
  name: hpe-ezmeral-csi-scc
defaultAddCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:my-hpe-ezmeral-csi-driver:csi-controller-sa
- system:serviceaccount:my-hpe-ezmeral-csi-driver:csi-nodeplugin-sa
- system:serviceaccount:my-hpe-ezmeral-csi-driver:csi-controller-nfs-sa
- system:serviceaccount:my-hpe-ezmeral-csi-driver:csi-nodeplugin-nfs-sa
- system:serviceaccount:my-hpe-ezmeral-csi-driver:hpe-ezmeral-csi-operator-sa
volumes:
- '*'
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'