############  Node Plugin DaemonSet ############

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: hpe-ezmeral-nfscsi-node
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: hpe-ezmeral-nfscsi-node
  template:
    metadata:
      labels:
        app: hpe-ezmeral-nfscsi-node
    spec:
      serviceAccount: csi-nodeplugin-nfs-sa
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      priorityClassName: {{ .Release.Namespace }}-nfs-critical
      containers:
        - name: csi-node-driver-registrar
          securityContext:
            privileged: true
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.12.0
          imagePullPolicy: "Always"
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/com.mapr.csi-nfskdf/nfscsi.sock"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/com.mapr.csi-nfskdf /registration/com.mapr.csi-nfskdf-reg.sock"]
          env:
            - name: ADDRESS
              value: /plugin/nfscsi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: registration-dir
              mountPath: /registration/
        - name: liveness-probe
          securityContext:
            privileged: true
          image: registry.k8s.io/sig-storage/livenessprobe:v2.14.0
          imagePullPolicy: "Always"
          args:
            - "--v=4"
            - "--csi-address=$(ADDRESS)"
            - "--probe-timeout=60s"
            - "--health-port=9809"
          env:
            - name: ADDRESS
              value: /plugin/nfscsi.sock
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
        - name: ezmeral-csi-driver
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: {{ .Values.nodeImage | quote }}
          imagePullPolicy: {{ .Values.pullPolicy | quote }}
          args :
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--maxvolumepernode=100"
            - "--maxlogsizemb=10"
            - "--createmountprefix=false"
            - "--v=4"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/nfscsi.sock
          ports:
          - containerPort: 9809
            name: healthz
            protocol: TCP
          livenessProbe:
            failureThreshold: 20
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 5
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
            - name: k8s-log-dir
              mountPath: /var/log/csi-maprkdf
            - name: timezone
              mountPath: /etc/localtime
              readOnly: true
            - name: core-path
              mountPath: /opt/cores
            - name: device-dir
              mountPath: /dev
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/com.mapr.csi-nfskdf
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: k8s-log-dir
          hostPath:
            path: /var/log/csi-maprkdf
            type: DirectoryOrCreate
        - name: timezone
          hostPath:
            path: /etc/localtime
        - name: core-path
          hostPath:
            path: /opt/cores
            type: DirectoryOrCreate
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory
